#!/bin/sh

echo "Applying Spotless..."
cd relentless-backend || exit 1
mvn spotless:apply
cd .. || exit 1

STAGED_FILES=$(git diff --cached --name-only)

if ! git diff --quiet
then
  for file in $STAGED_FILES
  do
    if [ -f "$file" ]
    then
      git add "$file"
    fi
  done
fi

exit 0
